### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Maikuolan** [Maikuolan/SFS-Mass-IP-Checker#3]
Looking for fresh ideas on ways to improve the project. :-)

If you've got any, feel free to suggest them here, or to fork the project, make some changes and send a pull request.

**Comment by mantasx** [comment]
yea it would be cool if you didnt have to upload a file in a format, id
like to upload a list of ips from my clipboard to a textbox. and also
export good users and bad users to clipboard as well, but only ips

Regards,
Mantas
